# Generated by Django 5.1.2 on 2024-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_chat_id",
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID чата",
                max_length=100,
                null=True,
                verbose_name="telegram_id",
            ),
        ),
    ]
