# Generated by Django 5.1.2 on 2024-10-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="habit",
            table="habits",
        ),
    ]
