# Generated by Django 5.1.2 on 2024-10-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_rename_time_habit_time_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="time_at",
            new_name="time",
        ),
    ]
