# Generated by Django 5.1.2 on 2024-10-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_remove_habit_is_public_habit_is_public_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                help_text="Введите время выполнения привычки",
                verbose_name="Время, когда нужно выполнить привычку",
            ),
        ),
    ]
